repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black src
        language: system
        types: [python]
    -   id: pylint
        name: pylint
        entry: pylint src
        language: system
        types: [python]
    - id
