repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black src/packaging_scout
        language: system
        types: [python]
    -   id: pylint
        name: pylint
        entry: pylint src/packaging_scout
        language: system
        types: [python]
    -   id: mypy
        name: mypy
        entry: mypy src/packaging_scout
        language: system
        types: [python]
    -   id: isort
        name: isort
        entry: isort src/packaging_scout
        language: system
        types: [python]

